src/Entity/Domains.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\DomainsRepository")
 * @ORM\Table(name="domains")
 */
class Domains
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

	/**
	 * @ORM\Column(type="string")
	 */
    private $url;

	/**
	 * @ORM\Column(type="string")
	 */
    private $ip;

	/**
	 * @ORM\Column(type="boolean")
	 */
    private $is_ip_ban;

	/**
	 * @ORM\Column(type="boolean")
	 */
    private $is_domain_ban;

	/**
	 * @ORM\Column(type="boolean", options={"default" = 1}))
	 */
    private $track;

	/**
	 * @ORM\Column(type="boolean", options={"default" = 1}))
	 */
    private $track_ip;

	/**
	 * @ORM\Column(type="integer", nullable=true)
	 */
	private $phone;

	/**
	 * @return mixed
	 */
	public function getTrack() {
		return $this->track;
	}

	/**
	 * @param mixed $track
	 */
	public function setTrack( $track ): void {
		$this->track = $track;
	}

	/**
	 * @return mixed
	 */
	public function getTrackIp() {
		return $this->track_ip;
	}

	/**
	 * @param mixed $track_ip
	 */
	public function setTrackIp( $track_ip ): void {
		$this->track_ip = $track_ip;
	}

	/**
	 * @return mixed
	 */
	public function getTrackDomain() {
		return $this->track_domain;
	}

	/**
	 * @param mixed $track_domain
	 */
	public function setTrackDomain( $track_domain ): void {
		$this->track_domain = $track_domain;
	}

	/**
	 * @ORM\Column(type="boolean", options={"default" = 1}))
	 */
    private $track_domain;

	/**
	 * @return mixed
	 */
	public function getCategory() {
		return $this->category;
	}

	/**
	 * @param mixed $category
	 */
	public function setCategory( $category ): void {
		$this->category = $category;
	}

	/**
	 * @ORM\Column(type="integer", nullable=true)
	 */
    private $category;
	/**
	 * @return mixed
	 */
	public function getId() {
		return $this->id;
	}

	/**
	 * @param mixed $id
	 *
	 * @return Domains
	 */
	public function setId( $id ) {
		$this->id = $id;

		return $this;
	}

	/**
	 * @return mixed
	 */
	public function getUrl() {
		return $this->url;
	}

	/**
	 * @param mixed $url
	 *
	 * @return Domains
	 */
	public function setUrl( $url ) {
		$this->url = $url;

		return $this;
	}

	/**
	 * @return mixed
	 */
	public function getIp() {
		return $this->ip;
	}

	/**
	 * @param mixed $ip
	 *
	 * @return Domains
	 */
	public function setIp( $ip ) {
		$this->ip = $ip;

		return $this;
	}

	/**
	 * @return mixed
	 */
	public function getisIpBan() {
		return $this->is_ip_ban;
	}

	/**
	 * @param mixed $is_ip_ban
	 *
	 * @return Domains
	 */
	public function setIsIpBan( $is_ip_ban ) {
		$this->is_ip_ban = $is_ip_ban;

		return $this;
	}

	/**
	 * @return mixed
	 */
	public function getPhone() {
		return $this->phone;
	}

	/**
	 * @param mixed $phone
	 */
	public function setPhone( $phone ): void {
		$this->phone = $phone;
	}

	/**
	 * @return mixed
	 */
	public function getIsDomainBan() {
		return $this->is_domain_ban;
	}

	/**
	 * @param mixed $is_domain_ban
	 *
	 * @return Domains
	 */
	public function setIsDomainBan( $is_domain_ban ) {
		$this->is_domain_ban = $is_domain_ban;

		return $this;
	}



}

src/Entity/Phone.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PhoneRepository")
 */
class Phone
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

	/**
	 * @ORM\Column(type="string")
	 */
    private $phone_number;

	/**
	 * @return mixed
	 */
	public function getId() {
		return $this->id;
	}

	/**
	 * @param mixed $id
	 */
	public function setId( $id ): void {
		$this->id = $id;
	}

	/**
	 * @return mixed
	 */
	public function getPhoneNumber() {
		return $this->phone_number;
	}

	/**
	 * @param mixed $phone_number
	 */
	public function setPhoneNumber( $phone_number ): void {
		$this->phone_number = $phone_number;
	}


}

src/Controller/DomainController.php
<?php

namespace App\Controller;

use App\Entity\Phone;
use App\Entity\Category;
use App\Entity\Domains;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class DomainController extends Controller {

	/**
	 * @Route("/add-domain", methods={"POST"})
	 */
	public function addDomain( Request $request, LoggerInterface $logger ) {

		$checkDC = new CheckDomainsController();
		$domain  = $request->get( 'domain_url' );
		$category_id  = $request->get( 'category_id' );
		$phone_id  = $request->get( 'phone_id' );

		$new_domainDB = array(
			'url'           => $domain,
			'is_ip_ban'     => false,
			'is_domain_ban' => false,
			'category_id'   => $category_id,
			'phone_id'      => $phone_id,
			'track'         => false,
			'track_domain'  => false,
			'track_ip'      => false,
		);
		if ( filter_var( $domain, FILTER_VALIDATE_IP ) ) {
			$respIP = $checkDC->checkAntizapretSite( $domain );

			if ( isset( $respIP->register ) ) {
				$new_domainDB['is_ip_ban'] = true;
			}
			$new_domainDB['ip'] = $domain;
		} else {
			$ip = $this->checkIpByDomain($domain);
			$respIP = $checkDC->checkAntizapretSite( $ip );
			$respDomain = $checkDC->checkAntizapretSite( $domain );

			if ( isset( $respIP->register ) ) {
				$new_domainDB['is_ip_ban'] = true;
			}
			if ( isset( $respDomain->register ) ) {
				$new_domainDB['is_domain_ban'] = true;
			}

			$new_domainDB['ip'] = $ip;
		}

		$id = $this->saveToDb( $new_domainDB );
		$new_domainDB['id'] = $id;
		return $this->json( $new_domainDB );
	}

	/**
	 * @Route("/delete-domain", methods={"POST"})
	 */
	public function deleteDomain( Request $request ) {
		$id = $request->get( 'domain_id' );
		$em     = $this->getDoctrine()->getManager();
		$domain = $em->getRepository( 'App:Domains' )->find( $id );

		$em->remove($domain);
		$em->flush();
		return $this->json($domain);
	}

	/**
	 * @Route("/get-by-category", methods={"POST"})
	 */
	public function getByCategory( Request $request ) {
		$categoryId     = $request->get( 'category_id' );
		$domainsRep     = $this->getDoctrine()->getRepository(Domains::class );
		$categoryRep    = $this->getDoctrine()->getRepository(Category::class);
		$phoneRep       = $this->getDoctrine()->getRepository(Phone::class);
		
		$categories     = $categoryRep->find($categoryId);
		$domains        = $domainsRep->findBy(['category' => $categoryId]);
		$phones         = $phoneRep->findAll();

		$domainArr      = array();
		foreach ( $domains as $domain ) {
			$phoneId        = null;
			$phoneNumber    = null;
			foreach ($phones as $phone){
				if ( $phone->getId() === $domain->getPhone() ) {
					$phoneNumber    = $phone->getPhoneNumber();
					$phoneId        = $phone->getId();
				}
			}
			$domainArr[] = [
				'id'            =>  $domain->getId(),
				'url'           =>  $domain->getUrl(),
				'ip'            =>  $domain->getIp(),
				'ban_domain'    =>  $domain->getisDomainBan(),
				'ban_ip'        =>  $domain->getisIpBan(),
				'category_name' =>  $categories->getName(),
				'category_id'   =>  $categoryId,
				'phone_id'      =>  $phoneId,
				'phone_number'  =>  $phoneNumber,
				'track'         =>  $domain->getTrack(),
				'track_ip'      =>  $domain->getTrackIp(),
				'track_domain'  =>  $domain->getTrackDomain(),
			];
		}
		return $this->json($domainArr );
	}

	/**
	 * @Route("/get-by-phone", methods={"POST"})
	 */
	public function getByPhone( Request $request ) {
		$phoneId        = $request->get( 'phone_id' );

		$domainsRep     = $this->getDoctrine()->getRepository(Domains::class );
		$categoryRep    = $this->getDoctrine()->getRepository(Category::class);
		$phoneRep       = $this->getDoctrine()->getRepository(Phone::class);

		$phones         = $phoneRep->find($phoneId);
		$domains        = $domainsRep->findBy(['phone' => $phoneId]);
		$categories     = $categoryRep->findAll();

		$domainArr      = array();
		foreach ( $domains as $domain ) {
			$categoryId        = null;
			$categoriesName    = null;
			foreach ($categories as $category){
				if ( $category->getId() === $domain->getCategory() ) {
					$categoriesName = $category->getName();
					$phoneId        = $category->getId();
				}
			}
			$domainArr[] = [
				'id'            =>  $domain->getId(),
				'url'           =>  $domain->getUrl(),
				'ip'            =>  $domain->getIp(),
				'ban_domain'    =>  $domain->getisDomainBan(),
				'ban_ip'        =>  $domain->getisIpBan(),
				'category_name' =>  $categoriesName,
				'category_id'   =>  $categoryId,
				'phone_id'      =>  $phoneId,
				'phone_number'  =>  $phones->getPhoneNumber(),
				'track'         =>  $domain->getTrack(),
				'track_ip'      =>  $domain->getTrackIp(),
				'track_domain'  =>  $domain->getTrackDomain(),
			];
		}
		return $this->json($domainArr );
	}

	/**
	 * @Route("/get-all-domain", methods={"POST"})
	 */
	public function getAllDomains( Request $request ) {
		$domainsRep     = $this->getDoctrine()->getRepository( Domains::class );
		$categoryRep    = $this->getDoctrine()->getRepository(Category::class);
		$phoneRep       = $this->getDoctrine()->getRepository(Phone::class);

		$category       = $categoryRep->findAll();
		$domains        = $domainsRep->findAll();
		$phones         = $phoneRep->findAll();

		$domainArr = array();
		foreach ( $domains as $domain ) {
			$category_name  = null;
			$category_id    = null;
			$phoneId        = null;
			$phoneNumber    = null;
			foreach ($phones as $phone){
				if ( $phone->getId() === $domain->getPhone() ) {
					$phoneNumber    = $phone->getPhoneNumber();
					$phoneId        = $phone->getId();
				}
			}
			foreach ($category as $cat){
				if ( $cat->getId() === $domain->getCategory() ) {
					$category_name  = $cat->getName();
					$category_id    = $cat->getId();
				}
			}
			$domainArr[] = [
				'id'            =>  $domain->getId(),
				'url'           =>  $domain->getUrl(),
				'ip'            =>  $domain->getIp(),
				'ban_domain'    =>  $domain->getisDomainBan(),
				'ban_ip'        =>  $domain->getisIpBan(),
				'category_name' =>  $category_name,
				'category_id'   =>  $category_id,
				'phone_id'      =>  $phoneId,
				'phone_number'  =>  $phoneNumber,
				'track'         =>  $domain->getTrack(),
				'track_ip'      =>  $domain->getTrackIp(),
				'track_domain'  =>  $domain->getTrackDomain(),

			];
		}
		return $this->json($domainArr );
	}

	public function checkIpByDomain( $domain ) {
		return gethostbyname( $domain );
	}

	public function saveToDb( $arr ) {
		$em     = $this->getDoctrine()->getManager();
		$domain = new Domains();
		$domain
			->setUrl( $arr['url'] )
			->setIp( $arr['ip'] )
			->setIsIpBan( $arr['is_ip_ban'] )
			->setIsDomainBan( $arr['is_domain_ban'] );

		$domain->setTrack($arr['track']);
		$domain->setTrackDomain($arr['track_domain']);
		$domain->setTrackIp( $arr['track_ip'] );

		if ( $arr['category_id'] != 'null' ) {
			$domain->setCategory( $arr['category_id'] );
		}
		if ( $arr['phone_id'] != 'null' ) {
			$domain->setPhone( $arr['phone_id'] );
		}
		$em->persist( $domain );

		$em->flush();

		return $domain->getId();
	}
}

templates/domains/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <table class="uk-table uk-table-middle" id="table_banControlSystem">
        <thead>
        <tr>
            <th><span> ID </span></th>
            <th><span> Домен   </span></th>
            <th><span> status  </span></th>
            <th><span> IP </span></th>
            <th><span> Категория  </span></th>
            <th><span> Телефон  </span></th>
            <th><span> Oтслеживать  </span></th>
            <th><span> оповещение по домену  </span></th>
            <th><span> оповещение по IP  </span></th>
            <th><span> Удалить </span></th>
        </tr>
        </thead>
        <tbody>
        {% for domain in domains %}
            <tr>
                <td>{{ domain.id }}</td>
                <td>
                    <a class="ban_domain" href="//{{ domain.url }}" target="_blank">{{ domain.url }}</a>
                </td>
                <td>
                    <span class="ban_value">
                        {% if domain.isDomainBan == true and domain.isIpBan == true %}
                            domain-ban  ip-ban
                        {% elseif domain.isDomainBan == true %}
                            domain-ban
                        {% elseif  domain.isIpBan == true %}
                            ip-ban
                        {% else %}
                            ok
                        {% endif %}
                    </span>
                </td>
                <td>
                    <span class="ban_ip">{{ domain.ip }}</span>
                </td>
                <td>
                    <span class="ban_ip" span_dom_cat="{{ domain.category }}">
                        {% for category in categories %}
                            {% if domain.category == category.id %}
                                {{ category.name }}
                            {% endif %}
                        {% endfor %}
                        {% if domain.category is null %}
                            <select class="select_domain_category" domain_id="{{ domain.id }}">
                                <option value="null">без категории</option>
                                {% for category in categories %}
                                    <option value="{{ category.id }}">{{ category.name }}</option>
                                {% endfor %}
                            </select>
                        {% endif %}
                    </span>
                </td>
                <td>
                    <span span_dom_phone="{{ domain.phone }}">
                        {% for phone in phones %}
                            {% if domain.phone == phone.id %}
                                {{ phone.phoneNumber }}
                            {% endif %}
                        {% endfor %}
                        {% if domain.phone is null %}
                            <select class="select_domain_phone" domain_id="{{ domain.id }}">
                                <option value="null">телефоныи</option>
                                    {% for phone in phones %}
                                        <option value="{{ phone.id }}">{{ phone.phoneNumber }}</option>
                                    {% endfor %}
                                </select>
                        {% endif %}
                    </span>

                </td>
                <td>
                    <label class="ban_track">
                        <input class="ban_checkbox" type="checkbox" {{ domain.track ? 'checked' : '' }}
                               track={{ domain.id }}>
                        <span class="ban_checkbox__vision"></span>
                    </label>
                </td>
                <td><label class="ban_domainAlert">
                        <input class="ban_checkbox" type="checkbox" {{ domain.trackDomain? 'checked' : '' }}
                               track_domain={{ domain.id }}>
                        <span class="ban_checkbox__vision"></span>
                    </label>
                </td>
                <td><label class="ban_IPAlert">
                        <input class="ban_checkbox" type="checkbox" {{ domain.trackIp ? 'checked' : '' }}
                               track_ip={{ domain.id }}>
                        <span class="ban_checkbox__vision"></span>
                    </label></td>
                <td>
                    <button class="btn_delite" type="button" domain_id="{{ domain.id }}"></button>
                </td>
            </tr>
        {% endfor %}
    </table>

    <button id="btn_addAdress" class="uk-button uk-button-secondary uk-button-small" type="button">add</button>

    <div class="bl_addAdress">

        <button id="btn_close__addAdress" type="button"></button>


        <input class="addItAdress" type="text" title="addIpAdress" placeholder="Добавить домен...">
        <button class="bl_addAdress__btn uk-button uk-button-secondary" id="addNewDomain" type="button">Добавить
        </button>
        <input class="addItCategorie" type="text" title="addIpAdress" placeholder="Добавить категорию...">
        <button class="bl_addAdress__btn uk-button uk-button-secondary" id="addNewCategory" type="button">Добавить
        </button>
        <input class="addItPhone" type="text" title="addPhone" placeholder="Добавить телефон...">
        <button class="bl_addAdress__btn uk-button uk-button-secondary" id="addNewPhone" type="button">Добавить</button>

        <select class="select_chooseCategory" name="" id="">
            <option value="null">Категории</option>

            {% for category in categories %}
                <option value="{{ category.id }}">{{ category.name }}</option>
            {% endfor %}

        </select>

        <select class="select_choosePhone" name="" id="">
            <option value="null">Телефон</option>

            {% for phone in phones %}
                <option value="{{ phone.id }}">{{ phone.phoneNumber }}</option>
            {% endfor %}

        </select>
    </div>


    <button id="btn_filters" class="uk-button uk-button-secondary uk-button-small" type="button">search</button>

    <div class="bl_filters">

        <button id="btn_close__filters" type="button"></button>


        <p>Фильтрация по категориям</p>
        <div class="bl_categories" id="categoryFilter">
            <div class="bl_categories__item">
                <label class="bl_categories__label">
                    <input type="checkbox" name="checkbox_categories" checked filterStatus="all">
                    <span>Все</span>
                </label>
            </div>
            {% for category in categories %}
                <div class="bl_categories__item">
                    <label class="bl_categories__label">
                        <input type="checkbox" name="checkbox_categories" filterStatus="category"
                               category_id="{{ category.id }}">
                        <span>{{ category.name }}</span>
                    </label>
                    <button class="btn_categories__delite" type="button" category_id="{{ category.id }}"
                            delete_category></button>
                </div>
            {% endfor %}
        </div>

        <p>Фильтрация по телефонам</p>
        <div class="bl_categories" id="phoneFilter">
            <div class="bl_categories__item">
            </div>
            {% for phone in phones %}
                <div class="bl_categories__item">
                    <label class="bl_categories__label">
                        <input type="checkbox" name="checkbox_categories" class="domainByPhone"
                               filterStatus="phone" phone_id="{{ phone.id }}">
                        <span>{{ phone.phoneNumber }}</span>
                    </label>
                    <button class="btn_categories__delite" type="button" phone_id="{{ phone.id }}"
                            phone_delete></button>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/domains/test.html.twig
{% extends 'base.html.twig' %}


{% block body %}
    <div id="root"></div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('build/js/app.js') }}"></script>
{% endblock %}